### ISSUE TITLE
RuntimeError: Invalid spec, no package name found: <NULL>

### ISSUE THREAD

**Issue by mikemhenry** [jaimergp/condacolab#54]
```
Looking for: ['mdanalysis', 'click', 'coverage', 'ipywidgets=7', 'lomap2', 'lxml', 'mdtraj', 'nbval', 'networkx', 'nglview', 'notebook', 'openff-forcefields', 'openmm', 'openmmtools', 'pip', 'plugcli', 'pymbar', 'pytest', 'pytest-cov', 'pytest-xdist', 'pydantic', 'python=3.9', 'rdkit', 'typing_extensions', "gufe[version='>=0.7.1']", "openfe[version='>=0.7.1']", 'py3dmol']



  Pinned packages:

  - python 3.10.*
  - python_abi 3.10.* *cp310*
  - cudatoolkit 11.8.*



# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/lib/python3.10/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/conda_env/cli/main_update.py", line 132, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba_env.py", line 140, in mamba_install
        print(solver.explain_problems())
    RuntimeError: Invalid spec, no package name found: <NULL>

`$ /usr/local/bin/mamba update -n base -f /environment.yml`

  environment variables:
                 CIO_TEST=<not set>
COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer
COLAB_LANGUAGE_SERVER_PROXY=<set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/usr/local
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/lib:/usr/lib64-nvidia
               LD_PRELOAD=<not set>
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us
                          r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl
                          e-cloud-sdk/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               TCLLIBPATH=/usr/share/tcltk/tcllib1.20

     active environment : None
       user config file : /root/.condarc
 populated config files : /usr/local/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.31=0
                          __linux=5.10.147=0
                          __unix=0=0
       base environment : /usr/local  (writable)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/5.10.147+ ubuntu/20.04.5 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

I've attached the environment.yml that caused this, I was able to get `condacolab` installed and the check was fine, this is the command I used to install my env:
`!mamba env update -n base -f /environment.yml`
[environment.yml.txt](https://github.com/conda-incubator/condacolab/files/11357980/environment.yml.txt)

**Comment by mikemhenry** [comment]
Oh I think the python 3.9 pin is the problem
