### ISSUE TITLE
No package can be installed for pin: cudatoolkit 12.2.

### ISSUE THREAD

**Issue by pablo-arantes** [jaimergp/condacolab#60]
Hi,

Until yesterday, I was using CondaColab and everything was working perfectly. Unfortunately, today I encountered the following error:

```No package can be installed for pin: cudatoolkit 12.2.*

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = install(args, parser, "install")
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 547, in install
        solver.add_pin(final_spec)
    RuntimeError: No package can be installed for pin: cudatoolkit 12.2.*
```

It seems the error is related to Mamba, but I couldn't find any relevant information in their GitHub repository. 
Are you experiencing the same issue? Has anyone managed to resolve it?

Thank you,

Pablo

**Comment by kimjc95** [comment]
Same issue here!
I think the issue is due to the fact that there is no package named 'cudatoolkit' with the version >=12 on conda-forge channel.
Somehow the package name has been changed from 'cudatoolkit' to 'cuda-toolkit' on conda-forge or nvidia channel since the version 12.

**Comment by kimjc95** [comment]
I came up with a quick workaround.. just erase the pinned file form the conda-meta directory after installing the condacolab.

`!rm -rf /usr/local/conda-meta/pinned`

**Comment by kimjc95** [comment]
If you want to use the cuda-toolkit 12.2, you can run this code instead.

```
with open('/usr/local/conda-meta/pinned', 'w') as f:
    f.write("python 3.10.*\npython_abi 3.10.* *cp310*\ncuda-toolkit 12.2.*")
!mamba install -q -c nvidia cuda-toolkit=12.2 
```

**Comment by jaimergp** [comment]
Hi, I added a PR at #63. Nice to have a new CUDA deployed on Friday :P 

Let me know if the following installation from branch fixes the issue:

```python
!pip install -U https://github.com/conda-incubator/condacolab/archive/cuda-version-12.tar.gz
```
```python
import condacolab
condacolab.install()
```

**Comment by jaimergp** [comment]
Note that `conda-forge` only has 12.0 for now, but 12.1 and 12.2 are [on the way](https://github.com/conda-forge/conda-forge.github.io/issues/1963#issuecomment-1856268602), so for now I'm only pinning to 12.x (and not 12.2.x).

I guess it should be ok to [CUDA compatibility guarantees](https://docs.nvidia.com/deploy/cuda-compatibility/).

**Comment by sef43** [comment]
> ```python
> !pip install -U https://github.com/conda-incubator/condacolab/archive/cuda-version-12.tar.gz
> ```

This works for the OpenMM Colab notebooks. Thank you!

**Comment by raybellwaves** [comment]
I recently came across this. I ended up doing `!pip install -q condacolab` instead of `!pip install -q "https://github.com/conda-incubator/condacolab/archive/main.zip"`. Took me a while to notice commit happen in a the 0.1.x branch https://github.com/conda-incubator/condacolab/tree/0.1.x

**Comment by jaimergp** [comment]
This issue has been solved for a while in 0.1.x. I added a similar strategy for CUDA 13, even if it's not available on Colab yet. That should prevent issues like this in the future.
