### ISSUE TITLE
Pin to cudatoolkit 12.2.* preventing installation of multiple packages in colab

### ISSUE THREAD

**Issue by andrewsb8** [jaimergp/condacolab#62]
A pin of the cudatoolkit 12.2.* is impeding the ability to install packages like openmm and gcc-12.1. Here is an example output for installing openmm:

```
!mamba install openmm -c conda-forge -y
Looking for: ['openmm']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
No package can be installed for pin: cudatoolkit 12.2.*

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = install(args, parser, "install")
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 547, in install
        solver.add_pin(final_spec)
    RuntimeError: No package can be installed for pin: cudatoolkit 12.2.*

`$ /usr/local/bin/mamba install openmm -c conda-forge -y`

  environment variables:
                 CIO_TEST=<not set>
COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer
COLAB_LANGUAGE_SERVER_PROXY=<set>
               CONDA_ROOT=/usr/local
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
               LD_PRELOAD=<not set>
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us
                          r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl
                          e-cloud-sdk/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               TCLLIBPATH=/usr/share/tcltk/tcllib1.20

     active environment : None
       user config file : /root/.condarc
 populated config files : /usr/local/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=6.1.58=0
                          __unix=0=0
       base environment : /usr/local  (writable)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/6.1.58+ ubuntu/22.04.3 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

Manual specifications of cudatoolkit versions, like `!mamba install -c conda-forge cudatoolkit=11.8 -y` does not remove the "pin". This issue does not occur on local installations of conda, where the default cudatoolkit version for openmm seems to be 11.8 in the conda-forge repository.

**Comment by kimjc95** [comment]
Try this and let me know if this resolves the issue.
[https://github.com/conda-incubator/condacolab/issues/60#issuecomment-1858067919](url)

**Comment by andrewsb8** [comment]
It did, thanks! Your link was broken, it should be [this](https://github.com/conda-incubator/condacolab/issues/60#issuecomment-1858049998)

**Comment by kimjc95** [comment]
Sorry. Not used to Markdown yet..

**Comment by jaimergp** [comment]
Thanks for the report! Closing as duplicate. See comment in https://github.com/conda-incubator/condacolab/issues/60#issuecomment-1859867325 for a potential solution!
